name: Run Units Tests

on: [push]

jobs:
  run-unit-tests:
    name: Run Units Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - uses: pnpm/action-setup@v4
        with:
          node-version: 20
          cache: "pnpm"

      - run: pnpm ci

      - run: pnpm test
